### ISSUE TITLE
支援 npm/yarn 安裝

### ISSUE THREAD

**Issue by visioncan** [essoduke/jQuery-TWzipcode#17]
大大是否有考慮加入 package.json 支援使用 npm/yarn 安裝?
https://docs.npmjs.com/getting-started/publishing-npm-packages

**Comment by essoduke** [comment]
我還沒試過 npm publish，剛剛姑且試了一下... 不知道有沒有成功 XD

`npm install jquery-twzipcode`

**Comment by visioncan** [comment]
有的~ Thanks! 👍  https://www.npmjs.com/package/jquery-twzipcode
