### ISSUE TITLE
There is no git tags on GitHub repository

### ISSUE THREAD

**Issue by sufuf3** [essoduke/jQuery-TWzipcode#20]
Hi @essoduke ,
We are cdnjs team, we'd like to host this library.
The git auto-updater in [cdnjs](https://github.com/cdnjs/cdnjs) relies on [**git tags**](https://github.com/essoduke/jQuery-TWzipcode/tags) so that it can recognize the correct version and automatically update the repo.
Could you please add git tags for the repo? 

If you have any suggestions, please let me know.
Thank you.

---
Hi @essoduke 大大您好，
我是 CDNJS 的成員之一，我們想要收錄這個 library 到 CDNJS 中。
CDNJS 是一個前端的資源庫，我們目前已經收錄了 3241 個 library ，這數字還會再持續成長中。

在這邊想請問您是否能為這個 repository 添加 git tag 呢？
因為當新的版本釋出的時候，我們的 CDNJS bot 會根據 git tag 來自動添加版本。
在維護上也更加的方便，並且也可以讓更多人透過 CDN 的服務更快速的存取您的 library。

若以上有不妥之處，還請您見諒。
期待您的回覆。
謝謝！

cdnjs/cdnjs#9270

**Comment by essoduke** [comment]
標籤已加入（我應該沒弄錯...）
若不正確還煩請告知。

**Comment by sufuf3** [comment]
謝謝您 👍
