### ISSUE TITLE
npm 上的版本號需要修正

### ISSUE THREAD

**Issue by Knovour** [essoduke/jQuery-TWzipcode#22]
npm 上顯示的版本號不是 `1.7.14.1` 而是 `1.7.1-4.1`，造成 brunch 套件在打包檔案時會發生找不到對應版本的情形（會一直去找  `1.7.14.1` 找不到而報錯）。

**Comment by essoduke** [comment]
因為之前建立版本時沒有依照規則，所以造成版本號被 npm 改寫。
目前已修改版本號為 1.7.15-rc1
