### ISSUE TITLE
員林鎮已改制、頭份鎮將改制

### ISSUE THREAD

**Issue by rangilin** [essoduke/jQuery-TWzipcode#8]
http://civil.chcg.gov.tw/files/2_1040729_%E5%85%AC%E5%91%8A.pdf
8/8 員林鎮已改制成員林市，連結是政府公告

http://news.ltn.com.tw/news/politics/breakingnews/1381240
頭份鎮已通過要改制為頭份市，目前還找不到政府公告

FYI
Rangi

**Comment by essoduke** [comment]
感謝通知，已修改為改制後的資料了。
